---
abstract: 'ACL support for Catalyst applications.'
author:
  - 'Yuval Kogman <nothingmuch@woobling.org>'
build_requires:
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Authorization-ACL
no_index:
  directory:
    - inc
    - t
provides:
  Catalyst::Plugin::Authorization::ACL:
    file: lib/Catalyst/Plugin/Authorization/ACL.pm
    version: 0.14
  Catalyst::Plugin::Authorization::ACL::Engine:
    file: lib/Catalyst/Plugin/Authorization/ACL/Engine.pm
requires:
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Runtime: 5.80013
  Class::Data::Inheritable: 0
  Class::Throwable: 0
  MRO::Compat: 0
  Moose: 0
  Tree::Simple: 0
  Tree::Simple::Visitor::FindByPath: 0
  Tree::Simple::Visitor::GetAllDescendents: 0
  namespace::autoclean: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/trunk/Catalyst-Plugin-Authorization-ACL/
version: 0.14
