---
abstract: 'ACL support for Catalyst applications.'
author:
  - 'Yuval Kogman <nothingmuch@woobling.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.50
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Authorization-ACL
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.7000
  Class::Data::Inheritable: 0
  Class::Throwable: 0
  MRO::Compat: 0
  Tree::Simple::Visitor::FindByPath: 0
  Tree::Simple::Visitor::GetAllDescendents: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.11
